export enum PlanRestrictionType {
    MEMBER_COUNT_LIMIT = 'MEMBER_COUNT_LIMIT',
    MEMBER_COUNT_PER_NODE_LIMIT = 'MEMBER_COUNT_PER_NODE_LIMIT',
    PIPELINE_COUNT_LIMIT = 'PIPELINE_COUNT_LIMIT',
    INVOCATION_COUNT_PER_NODE_PER_HOUR_LIMIT = 'INVOCATION_COUNT_PER_NODE_PER_HOUR_LIMIT',
    RUNTIME_INTERACTION_ACCESSIBILITY = 'RUNTIME_INTERACTION_ACCESSIBILITY',
}
