# .github/workflows/publish.yml
name: Publish Node.js Package

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: npm i --legacy-peer-deps=true

      - name: Run build
        run: npm run build

      - name: Pack-up artifact
        run: |
          zip -r artifact.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: |
          github.ref == 'refs/heads/alpha' ||
          github.ref == 'refs/heads/beta' ||
          github.ref == 'refs/heads/released'
        with:
          name: artifact-${{ github.run_id }}
          path: artifact.zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: |
      github.ref == 'refs/heads/alpha' ||
      github.ref == 'refs/heads/beta' ||
      github.ref == 'refs/heads/released'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-${{ github.run_id }}

      - name: Extract artifact
        run: |
          unzip -o artifact.zip

      - name: Check cache
        run: |
          ls -al ./dist

      - name: Install dependencies
        run: npm i --legacy-peer-deps=true

      - name: Release with semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: node bin/nttc.js bump npm --type $BRANCH_NAME --token $NPM_TOKEN

      - name: Prepare NPMRC
        run: |
          echo "always-auth=true" >> ./.npmrc
          echo "@open-norantec:registry=https://registry.npmjs.org" >> ./.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc

      - name: Publish package
        run: npm publish
